skylines/frontend/forms/__init__.py
# flake8: noqa

from .file import MultiFileField
from .pilot import LoginForm
from .upload import UploadForm

skylines/frontend/forms/file.py
from flask_wtf.file import FileField
from wtforms.widgets import FileInput as _FileInput


class FileInput(_FileInput):
    def __init__(self, multiple=False):
        self.multiple = multiple

    def __call__(self, field, **kwargs):
        if self.multiple:
            kwargs['multiple'] = 'multiple'

        return super(FileInput, self).__call__(field, **kwargs)


class MultiFileField(FileField):
    widget = FileInput(multiple=True)

skylines/commands/tracking/__init__.py
from flask.ext.script import Manager

from .clear import Clear
from .export import Export
from .fill_missing_keys import FillMissingKeys
from .generate import Generate
from .generate_through_daemon import GenerateThroughDaemon
from .server import Server
from .ogn_gateway import OgnGateway
from .stats import Stats

manager = Manager(help="Perform operations related to live tracking")
manager.add_command('clear', Clear())
manager.add_command('export', Export())
manager.add_command('fill-missing-keys', FillMissingKeys())
manager.add_command('generate', Generate())
manager.add_command('generate-through-daemon', GenerateThroughDaemon())
manager.add_command('runserver', Server())
manager.add_command('runogngateway', OgnGateway())
manager.add_command('stats', Stats())

skylines/frontend/assets/__init__.py
# flake8: noqa

from .environment import Environment

skylines/frontend/templates/__init__.py
# -*- coding: utf-8 -*-
"""Templates package for the application."""

skylines/frontend/views/__init__.py
from .errors import register as register_error_handlers
from .i18n import register as register_i18n
from .login import register as register_login

from .about import about_blueprint, about
from .airport import airport_blueprint
from .aircraft_models import aircraft_models_blueprint
from .assets import assets_blueprint
from .cesium import cesium_blueprint
from .club import club_blueprint
from .clubs import clubs_blueprint
from .files import files_blueprint
from .flight import flight_blueprint
from .flights import flights_blueprint
from .livetrack24 import lt24_blueprint
from .notifications import notifications_blueprint
from .ranking import ranking_blueprint
from .search import search_blueprint
from .settings import settings_blueprint
from .statistics import statistics_blueprint
from .timeline import timeline_blueprint
from .track import track_blueprint
from .tracking import tracking_blueprint
from .upload import upload_blueprint
from .user import user_blueprint
from .users import users_blueprint
from .widgets import widgets_blueprint


def register(app):
    register_error_handlers(app)
    register_i18n(app)
    register_login(app)

    app.register_blueprint(about_blueprint, url_prefix='/about')
    app.register_blueprint(airport_blueprint, url_prefix='/airports')
    app.register_blueprint(aircraft_models_blueprint, url_prefix='/aircraft-models')
    app.register_blueprint(assets_blueprint)
    app.register_blueprint(cesium_blueprint, url_prefix='/cesium')
    app.register_blueprint(club_blueprint, url_prefix='/clubs/<club_id>')
    app.register_blueprint(clubs_blueprint, url_prefix='/clubs')
    app.register_blueprint(files_blueprint, url_prefix='/files')
    app.register_blueprint(flight_blueprint, url_prefix='/flights/<flight_id>')
    app.register_blueprint(flights_blueprint, url_prefix='/flights')
    app.register_blueprint(lt24_blueprint)
    app.register_blueprint(notifications_blueprint, url_prefix='/notifications')
    app.register_blueprint(ranking_blueprint, url_prefix='/ranking')
    app.register_blueprint(search_blueprint, url_prefix='/search')
    app.register_blueprint(settings_blueprint, url_prefix='/settings')
    app.register_blueprint(statistics_blueprint, url_prefix='/statistics')
    app.register_blueprint(timeline_blueprint, url_prefix='/timeline')
    app.register_blueprint(track_blueprint, url_prefix='/tracking/<user_id>')
    app.register_blueprint(tracking_blueprint, url_prefix='/tracking')
    app.register_blueprint(upload_blueprint, url_prefix='/flights/upload')
    app.register_blueprint(user_blueprint, url_prefix='/users/<user_id>')
    app.register_blueprint(users_blueprint, url_prefix='/users')
    app.register_blueprint(widgets_blueprint, url_prefix='/widgets')

    @app.context_processor
    def inject_debug():
        return dict(debug=app.debug)

    @app.route('/')
    def index():
        return about()

skylines/frontend/views/about.py
import os.path

from flask import Blueprint, render_template, current_app
from flask.ext.babel import _

from skylines.lib.helpers import markdown

about_blueprint = Blueprint('about', 'skylines')


@about_blueprint.route('/')
def about():
    return render_template('about.jinja')


@about_blueprint.route('/imprint')
def imprint():
    content = current_app.config.get(
        'SKYLINES_IMPRINT',
        'Please set the `SKYLINES_IMPRINT` variable in the config file.')

    content = markdown.convert(content)

    return render_template(
        'generic/page.jinja', title=_('Imprint'), content=content)


@about_blueprint.route('/team')
def skylines_team():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'AUTHORS.md')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = content.replace('Developers', _('Developers'))
    content = content.replace('Translators', _('Translators'))

    content = markdown.convert(content)

    return render_template('generic/page.jinja',
                           title=_('The SkyLines Team'),
                           content=content)


@about_blueprint.route('/license')
def license():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'LICENSE')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = '<pre>' + content + '</pre>'

    return render_template(
        'generic/page.jinja', title=_('License'), content=content)

skylines/frontend/views/aircraft_models.py
from flask import Blueprint, jsonify

from skylines.model import AircraftModel
from skylines.schemas import AircraftModelSchema

aircraft_models_blueprint = Blueprint('aircraft_models', 'skylines')


@aircraft_models_blueprint.route('/')
def index():
    models = AircraftModel.query() \
        .order_by(AircraftModel.kind) \
        .order_by(AircraftModel.name) \
        .all()

    return jsonify(models=AircraftModelSchema().dump(models, many=True).data)

skylines/frontend/views/airport.py
from flask import Blueprint, jsonify

from skylines.lib.dbutil import get_requested_record
from skylines.model import Airport

airport_blueprint = Blueprint('airport', 'skylines')


@airport_blueprint.route('/<int:airport_id>')
def index(airport_id):
    airport = get_requested_record(Airport, airport_id)

    json = {
        'id': airport.id,
        'name': unicode(airport),
        'countryCode': airport.country_code,
    }

    return jsonify(**json)

skylines/frontend/views/assets.py
from flask import Blueprint, current_app, send_from_directory

assets_blueprint = Blueprint('assets', 'skylines')


@assets_blueprint.route('/<path:filename>')
def static(filename):
    return send_from_directory(current_app.config.get('ASSETS_LOAD_DIR'), filename)


@assets_blueprint.route('/assets/<path:filename>')
def assets(filename):
    return send_from_directory(current_app.config.get('ASSETS_DIRECTORY'), filename)

skylines/frontend/views/cesium.py
from flask import Blueprint, current_app, send_from_directory
import os

cesium_blueprint = Blueprint('cesium', 'skylines')


@cesium_blueprint.route('/<path:filename>')
def index(filename):
    path = current_app.config.get('SKYLINES_CESIUM_PATH')
    path += '/' + os.path.dirname(filename) + '/'
    filename = os.path.basename(filename)

    return send_from_directory(path, filename)

skylines/frontend/views/club.py
from flask import Blueprint, render_template, g, request, jsonify

from skylines.database import db
from skylines.lib.dbutil import get_requested_record
from skylines.lib.vary import vary
from skylines.model import Club
from skylines.schemas import ClubSchema, ValidationError

club_blueprint = Blueprint('club', 'skylines')


@club_blueprint.url_value_preprocessor
def _pull_user_id(endpoint, values):
    g.club_id = values.pop('club_id')
    g.club = get_requested_record(Club, g.club_id)


@club_blueprint.url_defaults
def _add_user_id(endpoint, values):
    if hasattr(g, 'club_id'):
        values.setdefault('club_id', g.club_id)


@club_blueprint.route('/')
@vary('accept')
def index():
    if 'application/json' not in request.headers.get('Accept', ''):
        return render_template('ember-page.jinja', active_page='settings')

    json = ClubSchema().dump(g.club).data
    json['isWritable'] = g.club.is_writable(g.current_user)

    return jsonify(**json)


@club_blueprint.route('/pilots')
def pilots():
    return render_template('ember-page.jinja', active_page='settings')


@club_blueprint.route('/edit')
def edit():
    return render_template('ember-page.jinja', active_page='settings')


@club_blueprint.route('/', methods=['POST'])
def edit_post():
    json = request.get_json()
    if json is None:
        return jsonify(error='invalid-request'), 400

    try:
        data = ClubSchema(partial=True).load(json).data
    except ValidationError, e:
        return jsonify(error='validation-failed', fields=e.messages), 422

    if 'name' in data:
        name = data.get('name')

        if name != g.club.name and Club.exists(name=name):
            return jsonify(error='duplicate-club-name'), 422

        g.club.name = name

    if 'website' in data:
        g.club.website = data.get('website')

    db.session.commit()

    return jsonify()

skylines/frontend/views/clubs.py
from flask import Blueprint, render_template, request, jsonify
from sqlalchemy import func

from skylines.model import Club
from skylines.lib.vary import vary
from skylines.schemas import ClubSchema

clubs_blueprint = Blueprint('clubs', 'skylines')


@clubs_blueprint.route('/')
@vary('accept')
def index():
    if 'application/json' not in request.headers.get('Accept', ''):
        return render_template('ember-page.jinja', active_page='settings')

    clubs = Club.query().order_by(func.lower(Club.name))

    name_filter = request.args.get('name')
    if name_filter:
        clubs = clubs.filter_by(name=name_filter)

    return jsonify(clubs=ClubSchema(only=('id', 'name')).dump(clubs, many=True).data)

skylines/frontend/views/errors.py
from flask import render_template
from werkzeug.exceptions import (
    HTTPException, InternalServerError, RequestTimeout,
)


def register(app):
    """ Register error handlers on the given app """

    @app.errorhandler(400)
    @app.errorhandler(404)
    @app.errorhandler(500)
    def handle_error(e):
        if not isinstance(e, HTTPException):
            e = InternalServerError()

        return render_template(
            'error.jinja',
            code=e.code,
            name=e.name,
            description=e.description,
        ), e.code

    @app.errorhandler(EOFError)
    def handle_eof_error(e):
        return handle_error(RequestTimeout())

skylines/frontend/views/files.py
from flask import Blueprint, current_app, send_from_directory

files_blueprint = Blueprint('files', 'skylines')


@files_blueprint.route('/<path:filename>')
def index(filename):
    path = current_app.config.get('SKYLINES_FILES_PATH')
    return send_from_directory(path, filename)

skylines/views/settings.py
from flask import Blueprint, request, render_template, redirect, url_for, abort, g, flash
from flask.ext.babel import _

from sqlalchemy.sql.expression import and_, or_

from skylines.forms import (
    ChangePasswordForm, EditPilotForm, LiveTrackingSettingsForm,
    ChangeClubForm, CreateClubForm
)
from skylines.lib.dbutil import get_requested_record
from skylines.model import db, User, Club, Flight, IGCFile
from skylines.views.users import send_recover_mail
from skylines.model.event import (
    create_club_join_event
)

settings_blueprint = Blueprint('settings', 'skylines')


@settings_blueprint.before_request
def handle_user_param():
    """
    Extracts the `user` parameter from request.values, queries the
    corresponding User model and checks if the model is writeable by the
    current user.
    """

    if not g.current_user:
        abort(403)

    g.user_id = request.values.get('user')

    if g.user_id:
        g.user = get_requested_record(User, g.user_id)
    else:
        g.user = g.current_user

    if not g.user.is_writable(g.current_user):
        abort(403)

    g.logout_next = url_for("index")


@settings_blueprint.route('/')
def index():
    """ Redirects /settings/ to /settings/profile """
    return redirect(url_for('.profile', user=g.user_id))


@settings_blueprint.route('/profile', methods=['GET', 'POST'])
def profile():
    form = EditPilotForm(obj=g.user)
    if not form.validate_on_submit():
        return render_template('settings/profile.jinja', form=form)

    g.user.email_address = form.email_address.data
    g.user.first_name = form.first_name.data
    g.user.last_name = form.last_name.data

    unit_preset = request.form.get('unit_preset', 1, type=int)
    if unit_preset == 0:
        g.user.distance_unit = request.form.get('distance_unit', 1, type=int)
        g.user.speed_unit = request.form.get('speed_unit', 1, type=int)
        g.user.lift_unit = request.form.get('lift_unit', 0, type=int)
        g.user.altitude_unit = request.form.get('altitude_unit', 0, type=int)
    else:
        g.user.unit_preset = unit_preset

    db.session.commit()

    flash(_('Profile was saved.'), 'success')

    return redirect(url_for('.profile', user=g.user_id))


@settings_blueprint.route('/password', methods=['GET', 'POST'])
def password():
    form = ChangePasswordForm()

    form_validated = form.validate_on_submit()

    if request.method == 'POST' and not (
            g.user.validate_password(form.current_password.data) or
            g.current_user.is_manager()):
        form.current_password.errors.append(_('This password does not match your current password.'))
        form_validated = False

    if not form_validated:
        return render_template('settings/password.jinja', form=form)

    g.user.password = form.password.data
    g.user.recover_key = None

    db.session.commit()

    flash(_('Your password was changed.'), 'success')

    return redirect(url_for('.password', user=g.user_id))


@settings_blueprint.route('/password/recover')
def password_recover():
    if not g.current_user.is_manager():
        abort(403)

    g.user.generate_recover_key(request.remote_addr)
    send_recover_mail(g.user)
    flash('A password recovery email was sent to that user.')

    db.session.commit()

    return redirect(url_for('.password', user=g.user_id))


@settings_blueprint.route('/tracking', methods=['GET', 'POST'])
def tracking():
    form = LiveTrackingSettingsForm(obj=g.user)
    if not form.validate_on_submit():
        return render_template('settings/tracking.jinja', form=form)

    g.user.tracking_callsign = form.tracking_callsign.data
    g.user.tracking_delay = request.form.get('tracking_delay', 0)
    db.session.commit()

    flash(_('Live Tracking settings were saved.'), 'success')

    return redirect(url_for('.tracking', user=g.user_id))


@settings_blueprint.route('/tracking/generate-key')
def tracking_generate_key():
    g.user.generate_tracking_key()
    db.session.commit()

    return redirect(url_for('.tracking', user=g.user_id))


@settings_blueprint.route('/club', methods=['GET'])
def club():
    change_form = ChangeClubForm(club=g.user.club_id)
    create_form = CreateClubForm()

    if request.endpoint.endswith('.club_change'):
        if change_form.validate_on_submit():
            return club_change_post(change_form)

    if request.endpoint.endswith('.club_create'):
        if create_form.validate_on_submit():
            return club_create_post(create_form)

    return render_template(
        'settings/club.jinja',
        change_form=change_form, create_form=create_form)


@settings_blueprint.route('/club', methods=['POST'])
def club_change():
    return club()


@settings_blueprint.route('/club/create', methods=['POST'])
def club_create():
    return club()


def club_change_post(form):
    old_club_id = g.user.club_id
    new_club_id = form.club.data if form.club.data != 0 else None

    if old_club_id == new_club_id:
        return redirect(url_for('.club', user=g.user_id))

    g.user.club_id = new_club_id

    create_club_join_event(new_club_id, g.user)

    # assign the user's new club to all of his flights that have
    # no club yet
    flights = Flight.query().join(IGCFile)
    flights = flights.filter(and_(Flight.club_id == None,
                                  or_(Flight.pilot_id == g.user.id,
                                      IGCFile.owner_id == g.user.id)))
    for flight in flights:
        flight.club_id = g.user.club_id

    db.session.commit()

    flash(_('New club was saved.'), 'success')

    return redirect(url_for('.club', user=g.user_id))


def club_create_post(form):
    club = Club(name=form.name.data)
    club.owner_id = g.current_user.id
    db.session.add(club)

    db.session.flush()

    g.user.club = club

    create_club_join_event(club.id, g.user)

    db.session.commit()

    return redirect(url_for('.club', user=g.user_id))

skylines/frontend/templates/tracking/info.jinja
{% extends "base-page.jinja" %}
{% set active_page = "tracking" %}

{% block title %}{% trans %}Live Tracking{% endtrans %}{% endblock %}

{%- block content %}
<h3>{% trans %}What is it?{% endtrans %}</h3>
<p>
  {% trans %}SkyLines Live Tracking can be used to let others take part on your journeys while you're flying. It uses a very light-weight protocol that only transmits the necessary data and due to that it can also work in areas/altitudes where the reception isn't very good. To give you an example: A flight of 10 hours only uses about 340 KB of traffic when the positions are transmitted every 5 seconds!{% endtrans %}
</p>

<h3>{% trans %}Clients{% endtrans %}</h3>
<ul>
  <li><b>XCSoar:</b><br/>{% trans xcsoar_6_4='<a href="http://www.xcsoar.org/download/latest.html">XCSoar 6.4</a>' %}available starting with {{ xcsoar_6_4 }}{% endtrans %} (<a href="https://play.google.com/store/apps/details?id=org.xcsoar" target="_blank">Google Play</a>).
  {% trans %}Instructions are below.{% endtrans %}</li>
  <li><b>Gaggle:</b><br/>{% trans %}now available in the current version of Gaggle{% endtrans %}
  (<a href="https://play.google.com/store/apps/details?id=com.geeksville.gaggle" target="_blank">Google Play</a>)</li>
  <li>
    <b>{{ _('LiveTrack24 clients') }}:</b><br/>
    {{ _('You can also use all available applications that use the %(livetrack24)s protocol for sending your locations to SkyLines. Just use your Live Tracking Key as username, choose any password you want and configure %(server)s as the server.', livetrack24='<a href="http://www.livetrack24.com/docs/wiki/LiveTracking%20API">LiveTrack24</a>', server='<code>skylines.aero</code>') }}
  </li>
</ul>

<h3>{% trans %}Live Tracking Key{% endtrans %}</h3>
{% if g.current_user -%}
<p>
  {{ _('Your Live Tracking key is: %(key)s', key='<span class="label tracking-key">' + g.current_user.tracking_key_hex + '</span>') }}
</p>

<p>
  <a href="{{ url_for('settings.tracking') }}" class="btn btn-default btn-sm"><i class="icon-cog"></i> {{ _('Live Tracking Settings') }}</a>
</p>
{%- else %}
<p>{% trans url=url_for('login', next=request.url) %}You have to <a href="{{ url }}">login</a> to see you own personal Live Tracking key.{% endtrans %}</p>
{%- endif %}

<h3>XCSoar</h3>
<p>
  {% trans xcsoar='<a href="http://www.xcsoar.org" target="_blank">XCSoar</a>'%}In {{ xcsoar }}, open the <em>Setup System</em> dialog, click on <em>Setup</em> and then <em>Tracking</em>.  Turn SkyLines tracking on, and enter your Live Tracking key.{% endtrans %}
</p>
{%- endblock %}

skylines/frontend/templates/tracking/map.jinja
{% from "macros/links.jinja" import user_link %}

{% extends "base-fullscreen.jinja" %}
{% set active_page = "tracking" %}
{% set use_ember = true %}
{% set openlayers = true %}


{% block title -%}
{% if pilots|length == 1 -%}
{{ _('Live Tracking <small>of %(pilot)s</small>', pilot=user_link(pilots[0])) }}
{%- elif pilots|length == 2 -%}
{{ _('Live Tracking <small>of %(pilot)s and %(other_pilot)s</small>', pilot=user_link(pilots[0]), other_pilot=user_link(pilots[1])) }}
{%- else -%}
{{ _('Live Tracking <small>of %(pilot)s and %(num_pilots)d other pilots</small>', pilot=user_link(pilots[0]), num_pilots=(pilots|length - 1)) }}
{%- endif %}
{%- endblock %}


{%- block scripts %}
{{ super() }}

{% if flights -%}
<script type="text/javascript">
  $(function() {
    var map = window.flightMap.get('map');

    var slFlightDisplay = require('skylines/utils/flight-display').default;
    var slFlightTracking = require('skylines/utils/flight-tracking').default;
    var slMapClickHandler = require('skylines/utils/map-click-handler').default;

    var flights = window.fixCalcService.get('flights');

    var flight_display = slFlightDisplay.create({
      fixCalc: window.fixCalcService,
      flightMap: window.flightMap,
      fix_table: window.fixTable,
      baro: window.barogram
    });
    var flight_tracking = slFlightTracking.create({
      flight_display: flight_display,
      flights: flights,
    });

    {% for flight in flights -%}
      window.fixCalcService.addFlight({{ flight|tojson }});
    {%- endfor %}

    var extent = flights.getBounds();
    map.getView().fit(extent, map.getSize(), {padding: window.paddingFn()});

    // update flight track every 15 seconds
    setInterval(function() {
      flight_tracking.updateFlightsFromJSON();
    }, 15*1000);

    var map_click_handler = slMapClickHandler(map, flight_display);
  });
</script>
{%- endif %}
{%- endblock %}


{% block content -%}
{% if flights -%}
<div id="fullscreen-content" class="olFullscreen" data-component='tracking-page' data-attrs='{
  "pilots": {{ pilots_json|tojson }}
}'></div>
{%- else -%}
<p style="margin:10pt;margin-top:40pt;">
  {% if pilots_json|length == 1 -%}
  {% trans %}There is no live track of this pilot currently.{% endtrans %}
  {%- else -%}
  {% trans %}There are no live tracks of these pilots currently.{% endtrans %}
  {%- endif %}
</p>
{%- endif %}
{%- endblock %}