skylines/api/views/errors.py
from werkzeug.exceptions import HTTPException, InternalServerError
from .json import jsonify


def register(app):
    """
    Register error handlers on the given app

    :type app: flask.Flask
    """

    @app.errorhandler(400)
    @app.errorhandler(401)
    @app.errorhandler(403)
    @app.errorhandler(404)
    @app.errorhandler(405)
    @app.errorhandler(500)
    def handle_http_error(e):
        if not isinstance(e, HTTPException):
            e = InternalServerError()

        data = getattr(e, 'data', None)
        if data:
            message = data['message']
        else:
            message = e.description

        return jsonify({
            'message': message,
        }, status=e.code)

    @app.errorhandler(422)
    def handle_bad_request(err):
        # webargs attaches additional metadata to the `data` attribute
        data = getattr(err, 'data')
        if data:
            # Get validations from the ValidationError object
            messages = data['exc'].messages
        else:
            messages = ['Invalid request']

        return jsonify({
            'messages': messages,
        }, status=422)

    @app.errorhandler(TypeError)
    @app.errorhandler(ValueError)
    def raise_bad_request(e):
        return jsonify({
            'message': e.message,
        }, status=400)

    @app.errorhandler(LookupError)
    def raise_not_found(e):
        return jsonify({
            'message': e.message,
        }, status=404)

skylines/frontend/assets/__init__.py
# flake8: noqa

from .environment import Environment

skylines/frontend/templates/__init__.py
# -*- coding: utf-8 -*-
"""Templates package for the application."""

skylines/frontend/views/about.py
import os.path

from flask import Blueprint, render_template, current_app
from flask.ext.babel import _

from skylines.lib.helpers import markdown

about_blueprint = Blueprint('about', 'skylines')


@about_blueprint.route('/')
def about():
    return render_template('about.jinja')


@about_blueprint.route('/imprint')
def imprint():
    content = current_app.config.get(
        'SKYLINES_IMPRINT',
        'Please set the `SKYLINES_IMPRINT` variable in the config file.')

    content = markdown.convert(content)

    return render_template(
        'generic/page.jinja', title=_('Imprint'), content=content)


@about_blueprint.route('/team')
def skylines_team():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'AUTHORS.md')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = content.replace('Developers', _('Developers'))
    content = content.replace('Translators', _('Translators'))

    content = markdown.convert(content)

    return render_template('generic/page.jinja',
                           title=_('The SkyLines Team'),
                           content=content)


@about_blueprint.route('/license')
def license():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', '..', '..', 'LICENSE')
    with open(path) as f:
        content = f.read().decode('utf-8')

    content = '<pre>' + content + '</pre>'

    return render_template(
        'generic/page.jinja', title=_('License'), content=content)

skylines/frontend/views/aircraft_models.py
from flask import Blueprint, jsonify

from skylines.model import AircraftModel
from skylines.schemas import AircraftModelSchema

aircraft_models_blueprint = Blueprint('aircraft_models', 'skylines')


@aircraft_models_blueprint.route('/')
def index():
    models = AircraftModel.query() \
        .order_by(AircraftModel.kind) \
        .order_by(AircraftModel.name) \
        .all()

    return jsonify(models=AircraftModelSchema().dump(models, many=True).data)

skylines/frontend/views/airport.py
from flask import Blueprint, jsonify

from skylines.lib.dbutil import get_requested_record
from skylines.model import Airport

airport_blueprint = Blueprint('airport', 'skylines')


@airport_blueprint.route('/<int:airport_id>')
def index(airport_id):
    airport = get_requested_record(Airport, airport_id)

    json = {
        'id': airport.id,
        'name': unicode(airport),
        'countryCode': airport.country_code,
    }

    return jsonify(**json)

skylines/frontend/views/assets.py
from flask import Blueprint, current_app, send_from_directory

assets_blueprint = Blueprint('assets', 'skylines')


@assets_blueprint.route('/<path:filename>')
def static(filename):
    return send_from_directory(current_app.config.get('ASSETS_LOAD_DIR'), filename)


@assets_blueprint.route('/assets/<path:filename>')
def assets(filename):
    return send_from_directory(current_app.config.get('ASSETS_DIRECTORY'), filename)

skylines/frontend/views/cesium.py
from flask import Blueprint, current_app, send_from_directory
import os

cesium_blueprint = Blueprint('cesium', 'skylines')


@cesium_blueprint.route('/<path:filename>')
def index(filename):
    path = current_app.config.get('SKYLINES_CESIUM_PATH')
    path += '/' + os.path.dirname(filename) + '/'
    filename = os.path.basename(filename)

    return send_from_directory(path, filename)

skylines/frontend/views/club.py
from flask import Blueprint, render_template, g, request, jsonify

from skylines.database import db
from skylines.lib.dbutil import get_requested_record
from skylines.lib.vary import vary
from skylines.model import Club
from skylines.schemas import ClubSchema, ValidationError

club_blueprint = Blueprint('club', 'skylines')


@club_blueprint.url_value_preprocessor
def _pull_user_id(endpoint, values):
    g.club_id = values.pop('club_id')
    g.club = get_requested_record(Club, g.club_id)


@club_blueprint.url_defaults
def _add_user_id(endpoint, values):
    if hasattr(g, 'club_id'):
        values.setdefault('club_id', g.club_id)


@club_blueprint.route('/')
@vary('accept')
def index():
    if 'application/json' not in request.headers.get('Accept', ''):
        return render_template('ember-page.jinja', active_page='settings')

    json = ClubSchema().dump(g.club).data
    json['isWritable'] = g.club.is_writable(g.current_user)

    return jsonify(**json)


@club_blueprint.route('/pilots')
def pilots():
    return render_template('ember-page.jinja', active_page='settings')


@club_blueprint.route('/edit')
def edit():
    return render_template('ember-page.jinja', active_page='settings')


@club_blueprint.route('/', methods=['POST'])
def edit_post():
    json = request.get_json()
    if json is None:
        return jsonify(error='invalid-request'), 400

    try:
        data = ClubSchema(partial=True).load(json).data
    except ValidationError, e:
        return jsonify(error='validation-failed', fields=e.messages), 422

    if 'name' in data:
        name = data.get('name')

        if name != g.club.name and Club.exists(name=name):
            return jsonify(error='duplicate-club-name'), 422

        g.club.name = name

    if 'website' in data:
        g.club.website = data.get('website')

    db.session.commit()

    return jsonify()

skylines/frontend/views/clubs.py
from flask import Blueprint, render_template, request, jsonify
from sqlalchemy import func

from skylines.model import Club
from skylines.lib.vary import vary
from skylines.schemas import ClubSchema

clubs_blueprint = Blueprint('clubs', 'skylines')


@clubs_blueprint.route('/')
@vary('accept')
def index():
    if 'application/json' not in request.headers.get('Accept', ''):
        return render_template('ember-page.jinja', active_page='settings')

    clubs = Club.query().order_by(func.lower(Club.name))

    name_filter = request.args.get('name')
    if name_filter:
        clubs = clubs.filter_by(name=name_filter)

    return jsonify(clubs=ClubSchema(only=('id', 'name')).dump(clubs, many=True).data)

skylines/frontend/views/flight.py
import math
from datetime import datetime

from flask import Blueprint, request, render_template, redirect, url_for, abort, current_app, jsonify, g, flash, make_response
from flask.ext.babel import lazy_gettext as _

from sqlalchemy.orm import undefer_group, contains_eager
from sqlalchemy.sql.expression import func
from geoalchemy2.shape import to_shape
from datetime import timedelta

from skylines.database import db
from skylines.lib import files
from skylines.lib.dbutil import get_requested_record_list
from skylines.lib.xcsoar_ import analyse_flight
from skylines.lib.datetime import from_seconds_of_day
from skylines.lib.geo import METERS_PER_DEGREE
from skylines.lib.geoid import egm96_height
from skylines.lib.vary import vary
from skylines.model import (
    User, Flight, FlightPhase, Location, FlightComment,
    Notification, Event, FlightMeetings, AircraftModel,
)
from skylines.model.event import create_flight_comment_notifications
from skylines.model.flight import get_elevations_for_flight
from skylines.schemas import fields, FlightSchema, FlightCommentSchema, Schema, ValidationError
from skylines.worker import tasks
from redis.exceptions import ConnectionError

import xcsoar

flight_blueprint = Blueprint('flight', 'skylines')


def _reanalyse_if_needed(flight):
    if flight.needs_analysis:
        current_app.logger.info("Queueing flight %s for reanalysis" % flight.id)
        try:
            tasks.analyse_flight.delay(flight.id)
        except ConnectionError:
            current_app.logger.info('Cannot connect to Redis server')
            # analyse syncronously...
            analyse_flight(flight)
            db.session.commit()


@flight_blueprint.url_value_preprocessor
def _pull_flight_id(endpoint, values):
    g.flight_id = values.pop('flight_id')


def _patch_query(q):
    return q.join(Flight.igc_file) \
            .options(contains_eager(Flight.igc_file)) \
            .filter(Flight.is_viewable(g.current_user))


@flight_blueprint.before_request
def _query_flights():
    g.flights = get_requested_record_list(
        Flight, g.flight_id, patch_query=_patch_query)

    g.flight = g.flights[0]
    g.other_flights = g.flights[1:]

    if not g.flight.is_viewable(None):
        g.logout_next = url_for('index')

    map(_reanalyse_if_needed, g.flights)


@flight_blueprint.url_defaults
def _add_flight_id(endpoint, values):
    if hasattr(g, 'flight_id'):
        values.setdefault('flight_id', g.flight_id)


def _get_flight_path(flight, threshold=0.001, max_points=3000):
    num_levels = 4
    zoom_factor = 4
    zoom_levels = [0]
    zoom_levels.extend([round(-math.log(32.0 / 45.0 * (threshold * pow(zoom_factor, num_levels - i - 1)), 2)) for i in range(1, num_levels)])

    xcsoar_flight = xcsoar.Flight(files.filename_to_path(flight.igc_file.filename))

    if flight.qnh:
        xcsoar_flight.setQNH(flight.qnh)

    begin = flight.takeoff_time - timedelta(seconds=2 * 60)
    end = flight.landing_time + timedelta(seconds=2 * 60)

    if begin > end:
        begin = datetime.min
        end = datetime.max

    xcsoar_flight.reduce(begin=begin,
                         end=end,
                         num_levels=num_levels,
                         zoom_factor=zoom_factor,
                         threshold=threshold,
                         max_points=max_points)

    encoded_flight = xcsoar_flight.encode()

    points = encoded_flight['locations']
    barogram_t = encoded_flight['times']
    barogram_h = encoded_flight['altitude']
    enl = encoded_flight['enl']

    elevations_t, elevations_h = _get_elevations(flight)
    contest_traces = _get_contest_traces(flight)

    geoid_height = egm96_height(flight.takeoff_location) if flight.takeoff_location else 0

    return dict(points=points,
                barogram_t=barogram_t, barogram_h=barogram_h,
                enl=enl, contests=contest_traces,
                elevations_t=elevations_t, elevations_h=elevations_h,
                sfid=flight.id, geoid=geoid_height)


def _get_elevations(flight):
    elevations = get_elevations_for_flight(flight)

    # Encode lists
    elevations_t = xcsoar.encode([t for t, h in elevations], method="signed")
    elevations_h = xcsoar.encode([h for t, h in elevations], method="signed")

    return elevations_t, elevations_h


def _get_contest_traces(flight):
    contests = [dict(contest_type='olc_plus', trace_type='triangle'),
                dict(contest_type='olc_plus', trace_type='classic')]

    contest_traces = []

    for contest in contests:
        contest_trace = flight.get_optimised_contest_trace(contest['contest_type'], contest['trace_type'])
        if not contest_trace:
            continue

        fixes = map(lambda x: (x.latitude, x.longitude), contest_trace.locations)
        times = []
        for time in contest_trace.times:
            times.append(flight.takeoff_time.hour * 3600 + flight.takeoff_time.minute * 60 + flight.takeoff_time.second +
                         (time - flight.takeoff_time).days * 86400 + (time - flight.takeoff_time).seconds)

        contest_traces.append(dict(name=contest['contest_type'] + " " + contest['trace_type'],
                                   turnpoints=xcsoar.encode(fixes, floor=1e5, method="double"),
                                   times=xcsoar.encode(times, method="signed")))

    return contest_traces


PHASETYPE_IDS = {
    FlightPhase.PT_POWERED: u'powered',
    FlightPhase.PT_CIRCLING: u'circling',
    FlightPhase.PT_CRUISE: u'cruise',
}


CIRCDIR_IDS = {
    FlightPhase.CD_LEFT: u'left',
    FlightPhase.CD_MIXED: u'mixed',
    FlightPhase.CD_RIGHT: u'right',
    FlightPhase.CD_TOTAL: u'total',
}


class FlightPhaseSchema(Schema):
    circlingDirection = fields.Function(lambda phase: CIRCDIR_IDS.get(phase.circling_direction))
    type = fields.Function(lambda phase: PHASETYPE_IDS.get(phase.phase_type))
    secondsOfDay = fields.Int(attribute='seconds_of_day')
    startTime = fields.DateTime(attribute='start_time')
    duration = fields.TimeDelta()
    altDiff = fields.Float(attribute='alt_diff')
    distance = fields.Float()
    vario = fields.Float()
    speed = fields.Float()
    glideRate = fields.Float(attribute='glide_rate')
    fraction = fields.Float()
    count = fields.Int()


class ContestLegSchema(Schema):
    distance = fields.Float()
    duration = fields.TimeDelta()
    start = fields.Int(attribute='seconds_of_day')
    climbDuration = fields.TimeDelta(attribute='climb_duration')
    climbHeight = fields.Float(attribute='climb_height')
    cruiseDistance = fields.Float(attribute='cruise_distance')
    cruiseHeight = fields.Float(attribute='cruise_height')


def mark_flight_notifications_read(flight):
    if not g.current_user:
        return

    def add_flight_filter(query):
        return query.filter(Event.flight_id == flight.id)

    Notification.mark_all_read(g.current_user, filter_func=add_flight_filter)
    db.session.commit()


class MeetingTimeSchema(Schema):
    start = fields.DateTime()
    end = fields.DateTime()


class NearFlightSchema(Schema):
    flight = fields.Nested(FlightSchema, only=('id', 'pilot', 'pilotName', 'copilot', 'copilotName',
                                               'model', 'registration', 'competitionId', 'igcFile'))

    times = fields.Nested(MeetingTimeSchema, many=True)


@flight_blueprint.route('/')
@vary('accept')
def index():
    if 'application/json' in request.headers.get('Accept', ''):
        return jsonify(flight=FlightSchema().dump(g.flight).data)

    near_flights = FlightMeetings.get_meetings(g.flight).values()
    near_flights = NearFlightSchema().dump(near_flights, many=True).data

    comments = FlightCommentSchema().dump(g.flight.comments, many=True).data

    phases_schema = FlightPhaseSchema(only=(
        'circlingDirection',
        'type',
        'secondsOfDay',
        'startTime',
        'duration',
        'altDiff',
        'distance',
        'vario',
        'speed',
        'glideRate',
    ))

    phases = phases_schema.dump(g.flight.phases, many=True).data

    cruise_performance_schema = FlightPhaseSchema(only=(
        'duration',
        'fraction',
        'altDiff',
        'distance',
        'vario',
        'speed',
        'glideRate',
        'count',
    ))

    cruise_performance = cruise_performance_schema.dump(g.flight.cruise_performance).data

    circling_performance_schema = FlightPhaseSchema(only=(
        'circlingDirection',
        'count',
        'vario',
        'fraction',
        'duration',
        'altDiff',
    ))

    circling_performance = circling_performance_schema.dump(g.flight.circling_performance, many=True).data

    contest_leg_schema = ContestLegSchema()
    contest_legs = {}
    for type in ['classic', 'triangle']:
        legs = g.flight.get_contest_legs('olc_plus', type)
        contest_legs[type] = contest_leg_schema.dump(legs, many=True).data

    mark_flight_notifications_read(g.flight)

    return render_template(
        'flights/map.jinja',
        ids=map(lambda flight: flight.id, g.flights),
        flight=g.flight,
        flight_json=FlightSchema().dump(g.flight).data,
        near_flights=near_flights,
        other_flights=g.other_flights,
        comments=comments,
        contest_legs=contest_legs,
        phases=phases,
        performance=dict(circling=circling_performance, cruise=cruise_performance))


@flight_blueprint.route('/map')
def map_():
    return redirect(url_for('.index'))


@flight_blueprint.route('/json')
def json():
    # Return HTTP Status code 304 if an upstream or browser cache already
    # contains the response and if the igc file did not change to reduce
    # latency and server load
    # This implementation is very basic. Sadly Flask (0.10.1) does not have
    # this feature
    last_modified = g.flight.time_modified \
        .strftime('%a, %d %b %Y %H:%M:%S GMT')
    modified_since = request.headers.get('If-Modified-Since')
    etag = request.headers.get('If-None-Match')

skylines/frontend/templates/about.jinja
{% extends "base-page.jinja" %}
{% set active_page = "about" %}


{%- block content %}
<div id="about">
  <div class="row">
    <div class="col-md-12 tagline">
      <p class="lead pull-left">{% trans %}Welcome to SkyLines, your internet platform for flight sharing!{% endtrans %}</p>

      <div class="btn-group social-buttons pull-right visible-md visible-lg">
        <a href="https://www.facebook.com/skylines.project" class="btn btn-default" target="_blank"><i class="icon-facebook-sign"></i></a>
        <a href="https://twitter.com/skylinesproject" class="btn btn-default" target="_blank"><i class="icon-twitter"></i></a>
        <a href="https://plus.google.com/114462603028839635814" class="btn btn-default" target="_blank"><i class="icon-google-plus"></i></a>
        <a href="https://github.com/skylines-project/skylines" class="btn btn-default" target="_blank"><i class="icon-github-alt"></i></a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 banner">
      <div class="col-xs-3"><a href="{{ url_for('flight.index', flight_id=17613, baselayer='Google Physical', overlays='Airspace') }}"><img src="/images/about-1.jpeg" class="img-responsive"/></a></div>
      <div class="col-xs-3"><a href="{{ url_for('flight.index', flight_id=17537, baselayer='Empty', overlays='Airspace') }}"><img src="/images/about-2.jpeg" class="img-responsive"/></a></div>
      <div class="col-xs-3"><a href="{{ url_for('flight.index', flight_id=17567, baselayer='OpenStreetMap', overlays='Airspace') }}"><img src="/images/about-3.jpeg" class="img-responsive"/></a></div>
      <div class="col-xs-3"><a href="{{ url_for('flight.index', flight_id=17577, baselayer='Shaded Relief', overlays='Airspace') }}"><img src="/images/about-4.jpeg" class="img-responsive"/></a></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h2><a href="{{ url_for('flights.index') }}"><i class="icon-plane"></i> {% trans %}Flight Database{% endtrans %}</a></h2>
      <p>{% trans url=url_for('upload.index') %}<a href="{{ url }}">Upload</a> your IGC files and share them with your friends. We won't change your files or restrict you from downloading them again!{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><a href="{{ url_for('tracking.index') }}"><i class="icon-rss"></i> {% trans %}Live Tracking{% endtrans %}</a></h2>
      <p>{% trans url=url_for('tracking.info') %}Use your mobile phone to send position updates to SkyLines. Find out how it works <a href="{{ url }}">here</a>.{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><i class="icon-info-sign"></i> {% trans %}Flight Analysis{% endtrans %}</h2>
      <p>{% trans %}Use our analysis tools to have a closer look at your flights and how you might be able to improve them in the future.{% endtrans %}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h2><i class="icon-map-marker"></i> {% trans %}Task Planning{% endtrans %} <small>({% trans %}planned{% endtrans %})</small></h2>
      <p>{% trans prosoar='<a href="http://www.prosoar.de/" target="_blank">proSoar <i class="icon-external-link icon-small"></i></a>' %}Use your browser to plan your tasks before the flight and upload them quickly to your flight computer. Integration of {{ prosoar }} is planned.{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><i class="icon-trophy"></i> {% trans %}Competitions{% endtrans %} <small>({% trans %}planned{% endtrans %})</small></h2>
      <p>{% trans %}Create competitions to offer your spectators an even better live tracking experience by following all the participants on the same map.{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><i class="icon-check"></i> {% trans %}Achievements{% endtrans %} <small>({% trans %}planned{% endtrans %})</small></h2>
      <p>{% trans %}Challenge yourself by trying to complete all the achievements that SkyLines offers. Fly large triangles, long final glides or just do your first outlanding.{% endtrans %}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h2><i class="icon-group"></i> {% trans %}Social Network{% endtrans %}</h2>
      <p>{% trans url=(g.current_user and url_for('notifications.index') or url_for('timeline.index')) %}Skylines also has some social network aspects. You can comment on flights, follow your friends and get <a href="{{ url }}">notifications</a> if they do anything interesting.{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><i class="icon-cloud"></i> {% trans %}Open Data{% endtrans %}</h2>
      <p>{% trans license='<a href="http://opendatacommons.org/licenses/by/summary/" target="_blank">Open Data Commons Attribution License (ODBY) <i class="icon-external-link icon-small"></i></a></a>', welt2000='<a href="http://www.segelflug.de/vereine/welt2000/" target="_blank">WELT2000 <i class="icon-external-link icon-small"></i></a></a>' %}The SkyLines flight database is made available under the {{ license }}. Skylines is using waypoint data from the {{ welt2000 }} project.{% endtrans %}</p>
    </div>
    <div class="col-md-4">
      <h2><i class="icon-wrench"></i> {% trans %}Open Source{% endtrans %}</h2>
      <p>{% trans team_url=url_for('about.skylines_team'), license_url=url_for('about.license'), github='<a href="https://github.com/skylines-project/skylines#contact-and-contributing" target="_blank">GitHub <i class="icon-external-link icon-small"></i></a></a>' %}Skylines is a <a href="{{ team_url }}">community</a> project and entirely based on free software (<a href="{{ license_url }}">License</a>). Visit {{ github }} if you want to help!{% endtrans %}</p>
    </div>
  </div>
</div>
{%- endblock %}

skylines/frontend/templates/base-form.jinja
{% extends "base-page.jinja" %}

{% block content -%}
<div class="row">
  <div class="panel col-sm-8 col-sm-offset-2">
    {% block form %}{% endblock %}
  </div>
</div>
{%- endblock %}

skylines/frontend/templates/base-fullscreen.jinja
{% extends "base.jinja" %}
{% from 'topbar.jinja' import topbar with context %}
{% from 'macros/flash.jinja' import insert_flash_message with context %}

{% block body -%}
{{ topbar(active_page) }}

<div id="ember-application" class="container-fullscreen">
    {% block content %}{% endblock %}
</div>

{{ insert_flash_message(True) }}
{%- endblock %}

skylines/frontend/templates/base-page.jinja
{% extends "base.jinja" %}
{% from 'topbar.jinja' import topbar with context %}
{% from 'macros/flash.jinja' import insert_flash_message with context %}

{% block body -%}
{{ topbar(active_page) }}

<div id="ember-application">
{% block ember_application %}
<div class="container">
    <div class="content">
        {% if self.title() -%}
        <div class="page-header{% if header_tabs %} page-header-with-tabs{% endif %}">
            {%- if self.title_right() -%}
            <div class="pull-right">{%- block title_right %}{% endblock %}</div>
            {%- endif %}

            <h1>{{ self.title() }}</h1>

            {%- if header_tabs -%}
            <div class="page-header-tabs">
                <ul class="nav nav-tabs">
                    {% for href, id, caption in header_tabs -%}
                    <li{% if active_header_tab == id %} class="active"{% endif %}>
                        <a href="{{ href }}">{{ caption }}</a>
                    </li>
                    {%- endfor %}
                </ul>
            </div>
            {%- endif %}
        </div>
        {%- endif %}

        <div class="row">
            <div class="col-md-12">
                {{ insert_flash_message(False) }}
                {%- block content %}{% endblock %}
            </div>
        </div>
    </div>

    <p class="footer">
        {% block footer -%}
        &copy; <a href="{{ url_for('about.skylines_team') }}">{{ _('The SkyLines Team') }}</a> -
        <a href="{{ url_for('about.imprint') }}">{% trans %}Imprint{% endtrans %}</a>
        {%- endblock %}
    </p>
</div>
{% endblock %}
</div>
{%- endblock %}

skylines/frontend/templates/ember-page.jinja
{% extends "base-page.jinja" %}
{% set use_ember = true %}

{% block ember_application %}{% endblock %}

skylines/frontend/templates/error.jinja
<!doctype html>
<html>
<head>
<title>{{ code }} {{ name }}</title>
</head>
<body>
<h1>{{ name }}</h1>
{% if description %}<p>{{ description }}</p>{% endif %}
</body>
</html>

skylines/frontend/templates/login.jinja
{% extends "base-form.jinja" %}
{% set active_page = "login" %}

{% from "macros/form.jinja" import render_field %}

{% block title %}{% trans %}Login{% endtrans %}{% endblock %}

{% block form -%}
<form method="POST" action="{{ url_for('login', next=next) }}" role="form" class="form-login">
  {{ form.hidden_tag() }}
  {{ render_field(form.email_address) }}
  {{ render_field(form.password) }}
  {{ render_field(form.remember_me) }}
  <div class="form-group">
    <input class="form-control btn btn-primary" value="{{ _('Login') }}" type="submit"/>
  </div>

  <hr/>

  <div>
    <a href="{{ url_for('users.recover') }}">{% trans %}Forgot password?{% endtrans %}</a>
  </div>

  <div>
    <a href="{{ url_for('users.new') }}">{% trans %}Don't have an account?{% endtrans %}</a>
  </div>
</form>
{%- endblock %}